Imports

In [ ]:
import numpy as np
from helpers import create_band_matrix,create_forcing_matrix
from matrix_algorithms import solve_jacobi,OutputSolution

Exercise A

Create a system of equations for a1=5+e, where e is the fourth digit of your index,
a2=a3=-1.The size of the matrix N is defined in section 2 of this manual. b is a vector
of length N, whose first element is the value of sin(n-(f+1)), where f is the third digit of your index.

In [ ]:

index = 197839

thrid_digit = index // 1000 % 10 # 3rd digit of index
fourth_digit = index // 100 % 10 # 4th digit of index

before_last = index // 10 % 10 # before last digit of index
last_digit = index % 10 # last digit of index

a1 = 5 + fourth_digit# a1 = 5 + 4th digit of index
a2 = a3 = -1 

N = 1200 + 10 * before_last + last_digit

A = create_band_matrix(a1,a2,a3, N) 
b = create_forcing_matrix(N, thrid_digit + 1)

print(A)
print(b)


[[ 3 -1 -1 ...  0  0  0]
 [-1  3 -1 ...  0  0  0]
 [-1 -1  3 ...  0  0  0]
 ...
 [ 0  0  0 ...  3 -1 -1]
 [ 0  0  0 ... -1  3 -1]
 [ 0  0  0 ... -1 -1  3]]
[[ 0.98935825]
 [ 0.91794788]
 [ 0.3781055 ]
 ...
 [ 0.96749073]
 [-0.72202085]
 [-0.69618518]]


Exercise B
Implement iterative methods for solving systems of linear equations:
Jacobi and Gauss-Seidel. Describe how many iterations each method needs to determine the
solution of the system of equations from task A,assuming that the condition for completing the calculation
is to achieve a residuum norm of less than 10^-9.For both methods, show on the graph
how the norm of the residuum changes in successive iterations performed to determine the
solution(y-axis on a logarithmic scale).Compare the running times of both algorithms.

In [ ]:
result:OutputSolution = solve_jacobi(A, b)

print("Solution:", result.x)
print("Iterations:", result.iterations)
print("Errors:", result.errors)
print("Time:", result.time)

Current error: 49.482996027639466
Current error: 64.30920560711915
Current error: 84.96354695438798
Current error: 112.75662041223366
Current error: 149.89140263234924
Current error: 199.41427764020298
Current error: 265.4200571766756
Current error: 353.37868958819126
Current error: 470.58533626461394
Current error: 626.7649862559771
Current error: 834.8800390219976
Current error: 1112.207406782404
Current error: 1481.7745021506232
Current error: 1974.2734688368537


KeyboardInterrupt: 