Imports

In [1]:
import numpy as np
from helpers import create_band_matrix,create_forcing_matrix
from matrix_algorithms import solve_jacobi,solve_gauss_seidel, OutputSolution

Exercise A

Create a system of equations for a1=5+e, where e is the fourth digit of your index,
a2=a3=-1.The size of the matrix N is defined in section 2 of this manual. b is a vector
of length N, whose first element is the value of sin(n-(f+1)), where f is the third digit of your index.

In [2]:

index = 197839

thrid_digit = index // 1000 % 10 # 3rd digit of index
fourth_digit = index // 100 % 10 # 4th digit of index

before_last = index // 10 % 10 # before last digit of index
last_digit = index % 10 # last digit of index

a1 = 5 + fourth_digit# a1 = 5 + 4th digit of index
a2 = a3 = -1 

N = 1200 + 10 * before_last + last_digit

A = create_band_matrix(a1,a2,a3, N) 
b = create_forcing_matrix(N, thrid_digit + 1)

print(A)
print(b)


[[13 -1 -1 ...  0  0  0]
 [-1 13 -1 ...  0  0  0]
 [-1 -1 13 ...  0  0  0]
 ...
 [ 0  0  0 ... 13 -1 -1]
 [ 0  0  0 ... -1 13 -1]
 [ 0  0  0 ... -1 -1 13]]
[[ 0.98935825]
 [ 0.91794788]
 [ 0.3781055 ]
 ...
 [ 0.96749073]
 [-0.72202085]
 [-0.69618518]]


Exercise B
Implement iterative methods for solving systems of linear equations:
Jacobi and Gauss-Seidel. Describe how many iterations each method needs to determine the
solution of the system of equations from task A,assuming that the condition for completing the calculation
is to achieve a residuum norm of less than 10^-9.For both methods, show on the graph
how the norm of the residuum changes in successive iterations performed to determine the
solution(y-axis on a logarithmic scale).Compare the running times of both algorithms.

In [3]:
# jacobi:OutputSolution = solve_jacobi(A, b)

# print("Iterations:", jacobi.iterations)
# print("Errors:", jacobi.errors)
# print("Time:", jacobi.time)

gauss:OutputSolution = solve_gauss_seidel(A, b)

print("Solve:", gauss.x)
print("Iterations:", gauss.iterations)
print("Errors:", gauss.errors)
print("Time:", gauss.time)

Solve: [[ 0.08619333]
 [ 0.08713164]
 [ 0.04402346]
 ...
 [ 0.0725084 ]
 [-0.04886916]
 [-0.0517343 ]]
Iterations: 16
Errors: [inf, np.float64(57.69054235797828), np.float64(10.47822553267532), np.float64(1.9036792901819448), np.float64(0.3458883888986374), np.float64(0.06284844301803137), np.float64(0.011419912450782523), np.float64(0.0020751048536288147), np.float64(0.00037707508803551577), np.float64(6.85210433200765e-05), np.float64(1.2451617677779347e-05), np.float64(2.262713515089456e-06), np.float64(4.111806353379835e-07), np.float64(7.471981705281636e-08), np.float64(1.3578150941809443e-08), np.float64(2.4674427472159937e-09), np.float64(4.4838832454904943e-10)]
Time: 22.41893196105957
